services:
  - type: web
    name: gnxt-backend
    runtime: node
    repo: https://github.com/madhuragnxt/Gnxt-backend
    branch: main
    plan: free
    healthCheckPath: /health
    buildCommand: npm install
    startCommand: bash start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: MONGO_URI
        value: mongodb+srv://gnxt:gnxt%40123@cluster0.bnjgcin.mongodb.net/gnxt?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: gnxt_super_secret_2026
      - key: JWT_EXPIRES
        value: 7d
      - key: CORS_ORIGIN
        value: https://gnxt.vercel.app
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_USER
        value: divyamadhuratech@gmail.com
      - key: SMTP_PASS
        sync: false
