/**
 * seedTestData.js
 * ───────────────
 * Creates:
 *   1. Vehicle  — KL07DC9716  (GPS IMEI: 869833082438627)
 *   2. Driver   — Arun Kumar  (dummy details)
 *   3. Invoice  — dummy plant/invoice so shipment creation works
 *   4. Shipment — links vehicle + driver + invoice
 *   5. GPS fix  — pushes a real-looking location fix for KL07DC9716
 *                 so the tracking page shows live data immediately
 *
 * Run:  node src/scripts/seedTestData.js
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: join(__dirname, "../../.env") });

import Vehicle        from "../models/Vehicle.js";
import Driver         from "../models/Driver.js";
import Invoice        from "../models/invoice.model.js";
import Shipment       from "../models/shipment.model.js";
import VehicleLocation from "../models/VehicleLocation.js";

/* ── helpers ── */
const log  = (msg) => console.log(`  ✅  ${msg}`);
const warn = (msg) => console.log(`  ⚠️   ${msg}`);

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("\n🚀  Connected to MongoDB:", process.env.MONGO_URI);
  console.log("─".repeat(55));

  /* ── 1. VEHICLE ─────────────────────────────────── */
  let vehicle = await Vehicle.findOne({ vehicleNo: "KL07DC9716" });
  if (vehicle) {
    warn("Vehicle KL07DC9716 already exists — updating IMEI");
    vehicle.gpsImei = "869833082438627";
    await vehicle.save();
  } else {
    // Find last vehicleId to generate next sequence
    const last = await Vehicle.findOne().sort({ createdAt: -1 });
    let seq = 1;
    if (last?.vehicleId) {
      const n = parseInt(last.vehicleId.split("-")[1]);
      if (!isNaN(n)) seq = n + 1;
    }
    vehicle = await Vehicle.create({
      vehicleId:       `VEH-${String(seq).padStart(3, "0")}`,
      vehicleNo:       "KL07DC9716",
      type:            "Truck",
      model:           "Tata 407",
      capacityKg:      5000,
      insuranceExpiry: new Date("2027-12-31"),
      ownership:       "Company",
      gpsImei:         "869833082438627",
      status:          "Idle",
      availability:    "Available",
    });
    log(`Vehicle created — ${vehicle.vehicleNo}  (${vehicle.vehicleId})  IMEI: ${vehicle.gpsImei}`);
  }

  /* ── 2. DRIVER ──────────────────────────────────── */
  let driver = await Driver.findOne({ licenseNumber: "KL0720210012345" });
  if (driver) {
    warn("Driver already exists — skipping");
  } else {
    driver = await Driver.create({
      name:          "Arun Kumar",
      age:           34,
      phone:         "+91 94470 12345",
      licenseNumber: "KL0720210012345",
      driverType:    "Own",
      tripStatus:    "Idle",
      documents: {
        licenseExpiry:     new Date("2028-06-30"),
        insuranceExpiry:   new Date("2027-12-31"),
        medicalExamExpiry: new Date("2026-12-31"),
      },
    });
    log(`Driver created — ${driver.name}  (${driver.licenseNumber})`);
  }

  /* ── 3. INVOICE (dummy plant data) ──────────────── */
  const plantRef = "PLT-KL-001";
  let invoice = await Invoice.findOne({ plantReferenceNumber: plantRef });
  if (invoice) {
    warn("Invoice already exists — skipping");
  } else {
    invoice = await Invoice.create({
      plantReferenceNumber: plantRef,
      customerName:         "Kerala Tyre Distributors",
      invoiceNumber:        "INV-KL-2026-00001",
      invoiceDate:          new Date("2026-05-01"),
      location:             "Kochi, Kerala",
      status:               "Pending",
    });
    log(`Invoice created — ${invoice.invoiceNumber}  plant: ${plantRef}`);
  }

  /* ── 4. SHIPMENT ────────────────────────────────── */
  const existingShipment = await Shipment.findOne({ vehicleId: vehicle._id }).sort({ createdAt: -1 });
  let shipment;
  if (existingShipment) {
    warn(`Shipment already exists for this vehicle — ${existingShipment.shipmentId}`);
    shipment = existingShipment;
  } else {
    shipment = new Shipment({
      destinations: [
        {
          lrNumber:            "",   // auto-generated by pre-save hook
          plantReferenceNumber: plantRef,
          customerName:        invoice.customerName,
          deliveryLocation:    invoice.location,
          invoiceIds:          [invoice._id],
          totalTyres:          50,
          totalTubes:          50,
          totalFlaps:          20,
          weightKg:            800,
        },
      ],
      vehicleId:         vehicle._id,
      vehicleNumber:     vehicle.vehicleNo,
      vehicleCapacityKg: vehicle.capacityKg,
      driverId:          driver._id,
      driverName:        driver.name,
      driverPhone:       driver.phone,
      status:            "In Transit",
      dispatchDate:      new Date(),
      notes:             "Test shipment — GPS tracking validation",
    });
    await shipment.save();

    // Mark vehicle + driver as on trip
    await Vehicle.findByIdAndUpdate(vehicle._id, { availability: "On Trip", status: "In Transit" });
    await Driver.findByIdAndUpdate(driver._id,  { tripStatus: "Assigned", assignedVehicle: vehicle.vehicleNo });

    log(`Shipment created — ${shipment.shipmentId}`);
    log(`LR Number       — ${shipment.destinations[0].lrNumber}`);
  }

  /* ── 5. GPS FIX (Kochi, Kerala — near the vehicle's home base) ── */
  const fixTime = new Date();
  const gpsPayload = {
    t:         "G",
    time:      fixTime.getTime(),
    device_id: "869833082438627",
    hd:        92.5,          // heading East
    sp:        38.4,          // 38.4 km/h
    refid:     "seed-test-001",
    ns:        9,             // 9 satellites
    alt:       7.2,           // 7.2 m altitude (coastal Kerala)
    geo: {
      lat: 9.9312,            // Kochi, Kerala
      lng: 76.2673,
      acc: 3,                 // high accuracy
    },
    vehicle_id: "KL07DC9716",
  };

  await VehicleLocation.findOneAndUpdate(
    { vehicleNo: "KL07DC9716" },
    {
      $set: {
        deviceId:      gpsPayload.device_id,
        lat:           gpsPayload.geo.lat,
        lng:           gpsPayload.geo.lng,
        acc:           gpsPayload.geo.acc,
        speed:         gpsPayload.sp,
        heading:       gpsPayload.hd,
        altitude:      gpsPayload.alt,
        satellites:    gpsPayload.ns,
        fixTime,
        vehicleStatus: "Moving",
        rawPayload:    gpsPayload,
      },
      $push: {
        history: {
          $each: [{ lat: gpsPayload.geo.lat, lng: gpsPayload.geo.lng, speed: gpsPayload.sp, heading: gpsPayload.hd, fixTime, acc: gpsPayload.geo.acc }],
          $slice: -500,
        },
      },
    },
    { upsert: true, new: true }
  );
  log(`GPS fix stored   — lat: ${gpsPayload.geo.lat}, lng: ${gpsPayload.geo.lng}  speed: ${gpsPayload.sp} km/h`);

  /* ── SUMMARY ─────────────────────────────────────── */
  console.log("\n" + "─".repeat(55));
  console.log("📋  SUMMARY");
  console.log("─".repeat(55));
  console.log(`  Vehicle   : ${vehicle.vehicleNo}  (IMEI: ${vehicle.gpsImei})`);
  console.log(`  Driver    : ${driver.name}  (${driver.phone})`);
  console.log(`  Invoice   : ${invoice.invoiceNumber}  →  ${invoice.customerName}`);
  console.log(`  Shipment  : ${shipment.shipmentId}  →  Status: ${shipment.status}`);
  console.log(`  LR Number : ${shipment.destinations[0].lrNumber}`);
  console.log(`  GPS Fix   : Kochi, Kerala  (9.9312° N, 76.2673° E)`);
  console.log("\n  🔗  Tracking URL: http://localhost:5173/tracking/KL07DC9716");
  console.log("\n  📡  Webhook test:");
  console.log(`  curl -X POST http://localhost:5000/api/gps/webhook \\`);
  console.log(`    -H "Content-Type: application/json" \\`);
  console.log(`    -d '{"t":"G","time":${Date.now()},"device_id":"869833082438627","hd":92.5,"sp":45.0,"refid":"live-001","ns":9,"alt":7.2,"geo":{"lat":9.9312,"lng":76.2673,"acc":3},"vehicle_id":"KL07DC9716"}'`);
  console.log("─".repeat(55) + "\n");

  await mongoose.disconnect();
  console.log("✅  Done.\n");
}

seed().catch((err) => {
  console.error("❌  Seed failed:", err.message);
  process.exit(1);
});
